name: GitHub Pages Publisher
description: Deploys already generated static pages to GitHub Pages.
branding:
  icon: book
  color: gray-dark
inputs:
  defaultBranch:
    description: 'The default branch name for the repository, defaults to `master` for backwards-compatiblity reasons. Version 2.x will likely default to `main`.'
    required: false
  docsPath:
    description: 'The folder where the generated docs are located, defaults to `docs`.'
    required: false
  gitCommitEmail:
    description: The email to use when committing to the repository, defaults to the repository owner's fake GitHub email.
    required: false
    default: ''
  gitCommitFlags:
    description: 'Any extra `git commit` flags to pass, such as `--no-verify`.'
    default: ''
    required: false
  gitCommitUser:
    description: 'The value to set `git config user.name`, defaults to the repository owner.'
    required: false
  publishBranch:
    description: 'The branch name that GitHub Pages uses to build the website, defaults to `gh-pages`.'
    required: false
  showUnderscoreFiles:
    description: 'If set, adds a `.nojekyll` file to the root so files that start with `_` are accessible.'
    required: false
  versionDocs:
    description: 'If set, put docs for all branches and tags in their own subfolders, defaults to `false`.'
    required: false
runs:
  using: docker
  image: Dockerfile
